// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CommentLike struct {
	ID             string       `json:"id"`
	UserID         string       `json:"user_id"`
	CommentID      string       `json:"comment_id"`
	IsCommentLiked *bool        `json:"is_comment_liked,omitempty"`
	User           *User        `json:"user,omitempty"`
	Parent         *PostComment `json:"parent,omitempty"`
	CreatedAt      *string      `json:"created_at,omitempty"`
	UpdatedAt      *string      `json:"updated_at,omitempty"`
	DeletedAt      *string      `json:"deleted_at,omitempty"`
}

type InboxFile struct {
	ID        string  `json:"id"`
	InboxID   string  `json:"inbox_id"`
	Type      *string `json:"type,omitempty"`
	URL       *string `json:"url,omitempty"`
	Active    *bool   `json:"active,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	DeletedAt *string `json:"deleted_at,omitempty"`
}

type InboxGetAllBubble struct {
	Username    string `json:"username"`
	FullName    string `json:"full_name"`
	Avatar      string `json:"avatar"`
	LastMessage string `json:"last_message"`
	IsRead      bool   `json:"is_read"`
	CreatedAt   string `json:"created_at"`
}

type PostFile struct {
	ID        string  `json:"id"`
	PostID    string  `json:"post_id"`
	URL       *string `json:"url,omitempty"`
	Active    *bool   `json:"active,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	DeletedAt *string `json:"deleted_at,omitempty"`
}

type PostSave struct {
	ID        string  `json:"id"`
	UserID    string  `json:"user_id"`
	PostID    string  `json:"post_id"`
	Post      *Post   `json:"Post,omitempty"`
	User      *User   `json:"User,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
}

type Query struct {
}

type UserSearch struct {
	ID       string  `json:"id"`
	Username string  `json:"username"`
	FullName *string `json:"full_name,omitempty"`
	Avatar   *string `json:"avatar,omitempty"`
	Role     *bool   `json:"role,omitempty"`
	Active   *bool   `json:"active,omitempty"`
}
